image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Albedo Signer"
    command: |
      cd ~/.local/_client
      clear
      npm run start
  - name: Futurenet
    init: |
      docker pull stellar/quickstart:soroban-dev
    command: |
      docker run --rm -it \
      --name stellar \
      -p 8000:8000 \
      stellar/quickstart:soroban-dev \
      --futurenet \
      --enable-soroban-rpc
  - name: CLI - Futurenet
    env:
      SOROBAN_RPC_URL: "http://localhost:8000/soroban/rpc"
      SOROBAN_NETWORK_PASSPHRASE: "Test SDF Future Network ; October 2022"
    command: |
      source ~/.local/sq-bash-hook \
      clear
  - name: CLI - Sandbox
    init: |
      cargo clean
      cargo fetch
      # make build
      # cargo test -p soroban-hello-world-contract
    command: |
      gp open README.md
      clear

vscode:
  extensions:
    - vadimcn.vscode-lldb
    - rust-lang.rust-analyzer

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

ports:
  - name: Futurenet
    port: 8000
    visibility: public
    onOpen: ignore
  - name: Albedo Signer
    port: 3000
    visibility: public
    onOpen: ignore
  - port: 4226
    visibility: private
    onOpen: ignore
