[package]
name = "soroban-hello-world-contract"
version = "0.0.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = "0.3.1"

[dev_dependencies]
soroban-sdk = { version = "0.3.1", features = ["testutils"] }